package org.joaocastillo.com.controller;

public enum Pantallas {
    MENU, EMPRESAS, PRODUCTOS, TIPOS_DE_PLATOS, TIPOS_DE_EMPLEADOS, PRESUPUESTOS, PLATOS, PRODUCTOS_TIENE_PLATOS,
    SERVICIOS_TIENE_PLATOS, SERVICIOS_TIENE_EMPLEADOS, PROGRAMADOR, SERVICIOS, EMPLEADOS, CREATE_USER, LOGIN

}
