package org.joaocastillo.com.controller;

public enum Pantallas {
	MENU, EMPRESAS, PRODUCTOS, TIPOS_DE_PLATOS, TIPOS_DE_EMPLEADOS, PRESUPUESTOS, PLATOS, PRODUCTOS_TIENE_PLATOS,
	SERVICIOS_TIENE_PLATOS, SERVICIVIOS_TIENE_EMPLEADOS, PROGRAMADOR

}
